In [1]:
pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in e:\paula_w58gcxy\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.


In [2]:
#Se importan librerías
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

In [3]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_per.CSV' #Se carga el dataset de personas
df_dataset = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual está separado por comas
df_dataset.isnull().sum() #Se imprimen la cantidad de filas nulas por cada columna del dataset

U_DPTO                     0
U_MPIO                     0
P_SEXO                     0
P_EDADR                    0
PA1_GRP_ETNIC              0
PA_HABLA_LENG       42253080
PB_OTRAS_LENG       42253080
PB1_QOTRAS_LENG     43973903
PA1_CALIDAD_SERV    40872069
P_ALFABETA           3037781
P_NIVEL_ANOSR        3037781
P_TRABAJO            6682277
dtype: int64

In [4]:
df_dataset #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
0             91       1       2        2              6            NaN   
1             91       1       1        9              1            2.0   
2             91       1       2        3              6            NaN   
3             91       1       2        8              1            2.0   
4             91       1       1        1              6            NaN   
...          ...     ...     ...      ...            ...            ...   
44164412      99     773       2        4              6            NaN   
44164413      99     773       2        8              6            NaN   
44164414      99     773       2        3              6            NaN   
44164415      99     773       1        3              6            NaN   
44164416      99     773       1        9              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
0                   NaN              NaN               NaN         1.0   
1                   2.0              NaN               NaN         1.0   
2                   NaN              NaN               NaN         1.0   
3                   2.0              NaN               NaN         1.0   
4                   NaN              NaN               NaN         NaN   
...                 ...              ...               ...         ...   
44164412            NaN              NaN               NaN         1.0   
44164413            NaN              NaN               NaN         1.0   
44164414            NaN              NaN               NaN         1.0   
44164415            NaN              NaN               NaN         1.0   
44164416            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
0                   1.0        NaN  
1                   3.0        2.0  
2                   2.0        9.0  
3                   4.0        1.0  
4                   NaN        NaN  
...                 ...        ...  
44164412            3.0        NaN  
44164413            8.0        NaN  
44164414            2.0        NaN  
44164415            2.0        NaN  
44164416            7.0        NaN  

[44164417 rows x 12 columns]

In [5]:
#Se crean 6 variables las cuales tienen los códigos de departamento
#Esto se hace debido a que el dataset de personas es demasiado grande y se presentan problemas a la hora de hacer
#El pre-procesamiento de todo el dataset, por lo que, se procedió a generar datasets más pequeños y pre-procesarlos.
options= ["27","76","54","63","19","73"]
options1=["41","18","20","15","44"]
options2=["50","66","17","05","47","70"]
options3=["23","52","68","08","13","88"]
options4=["91","81","85","25","94","11"]
options5=["86","97","99","95"]

In [6]:
result_df=df_dataset[df_dataset['U_DPTO'].isin(options)] #Se asigna a result_df el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options
result_df #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
20512205      19       1       1       12              6            NaN   
20512206      19       1       2        4              6            NaN   
20512207      19       1       2        7              6            NaN   
20512208      19       1       1        6              6            NaN   
20512209      19       1       1       10              6            NaN   
...          ...     ...     ...      ...            ...            ...   
44050080      76     895       1        3              6            NaN   
44050081      76     895       1        3              6            NaN   
44050082      76     895       1        3              6            NaN   
44050083      76     895       1        3              6            NaN   
44050084      76     895       1        2              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
20512205            NaN              NaN               NaN         1.0   
20512206            NaN              NaN               NaN         1.0   
20512207            NaN              NaN               NaN         1.0   
20512208            NaN              NaN               NaN         1.0   
20512209            NaN              NaN               NaN         1.0   
...                 ...              ...               ...         ...   
44050080            NaN              NaN               NaN         1.0   
44050081            NaN              NaN               NaN         1.0   
44050082            NaN              NaN               NaN         1.0   
44050083            NaN              NaN               NaN         1.0   
44050084            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
20512205            4.0        5.0  
20512206            4.0        6.0  
20512207            9.0        1.0  
20512208            8.0        1.0  
20512209            4.0        1.0  
...                 ...        ...  
44050080            2.0        NaN  
44050081            2.0        NaN  
44050082            3.0        NaN  
44050083            2.0        NaN  
44050084            2.0        NaN  

[8575998 rows x 12 columns]

In [7]:
result_df2=df_dataset[df_dataset['U_DPTO'].isin(options1)] #Se asigna a result_df2 el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options1
result_df2 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
17713541      15       1       2       13              6            NaN   
17713542      15       1       2       11              6            NaN   
17713543      15       1       2        4              6            NaN   
17713544      15       1       1        3              6            NaN   
17713545      15       1       2        1              6            NaN   
...          ...     ...     ...      ...            ...            ...   
29612589      44     874       1        5              6            NaN   
29612590      44     874       1        5              6            NaN   
29612591      44     874       1        3              6            NaN   
29612592      44     874       1        6              1            1.0   
29612593      44     874       1       17              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
17713541            NaN              NaN               NaN         1.0   
17713542            NaN              NaN               NaN         1.0   
17713543            NaN              NaN               NaN         1.0   
17713544            NaN              NaN               NaN         1.0   
17713545            NaN              NaN               NaN         NaN   
...                 ...              ...               ...         ...   
29612589            NaN              NaN               NaN         1.0   
29612590            NaN              NaN               NaN         1.0   
29612591            NaN              NaN               NaN         1.0   
29612592            1.0              2.0               NaN         1.0   
29612593            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
17713541            2.0        1.0  
17713542            2.0        1.0  
17713543            4.0        7.0  
17713544            3.0        6.0  
17713545            NaN        NaN  
...                 ...        ...  
29612589            3.0        9.0  
29612590            3.0        9.0  
29612591            3.0        9.0  
29612592            3.0        9.0  
29612593            4.0        9.0  

[4428789 rows x 12 columns]

In [8]:
result_df3=df_dataset[df_dataset['U_DPTO'].isin(options2)] #Se asigna a result_df3 el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options2
result_df3 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
66056          5       1       1        5              6            NaN   
66057          5       1       2       11              6            NaN   
66058          5       1       2        7              6            NaN   
66059          5       1       2        1              6            NaN   
66060          5       1       1       11              6            NaN   
...          ...     ...     ...      ...            ...            ...   
39031443      70     823       1       15              6            NaN   
39031444      70     823       2       14              6            NaN   
39031445      70     823       1        6              6            NaN   
39031446      70     823       2        6              6            NaN   
39031447      70     823       2       10              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
66056               NaN              NaN               NaN         1.0   
66057               NaN              NaN               NaN         1.0   
66058               NaN              NaN               NaN         1.0   
66059               NaN              NaN               NaN         NaN   
66060               NaN              NaN               NaN         1.0   
...                 ...              ...               ...         ...   
39031443            NaN              NaN               NaN         1.0   
39031444            NaN              NaN               NaN         2.0   
39031445            NaN              NaN               NaN         1.0   
39031446            NaN              NaN               NaN         1.0   
39031447            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
66056               4.0        3.0  
66057               4.0        7.0  
66058               7.0        6.0  
66059               NaN        NaN  
66060               4.0        3.0  
...                 ...        ...  
39031443            2.0        7.0  
39031444           10.0        7.0  
39031445            4.0        1.0  
39031446            7.0        1.0  
39031447            2.0        7.0  

[10784810 rows x 12 columns]

In [9]:
result_df4=df_dataset[df_dataset['U_DPTO'].isin(options3)] #Se asigna a result_df4 el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options3
result_df4 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
6280347        8       1       1       12              6            NaN   
6280348        8       1       2       16              6            NaN   
6280349        8       1       1       17              6            NaN   
6280350        8       1       2        9              6            NaN   
6280351        8       1       1       11              6            NaN   
...          ...     ...     ...      ...            ...            ...   
38167407      68     895       1       13              6            NaN   
38167408      68     895       2       11              6            NaN   
38167409      68     895       1       13              6            NaN   
38167410      68     895       2       13              6            NaN   
38167411      68     895       1        6              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
6280347             NaN              NaN               NaN         1.0   
6280348             NaN              NaN               NaN         1.0   
6280349             NaN              NaN               NaN         1.0   
6280350             NaN              NaN               NaN         1.0   
6280351             NaN              NaN               NaN         1.0   
...                 ...              ...               ...         ...   
38167407            NaN              NaN               3.0         1.0   
38167408            NaN              NaN               3.0         1.0   
38167409            NaN              NaN               NaN         1.0   
38167410            NaN              NaN               NaN         1.0   
38167411            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
6280347             4.0        1.0  
6280348             8.0        9.0  
6280349             4.0        9.0  
6280350             7.0        7.0  
6280351             7.0        1.0  
...                 ...        ...  
38167407            2.0        9.0  
38167408            2.0        7.0  
38167409            2.0        1.0  
38167410            2.0        7.0  
38167411            5.0        9.0  

[9199982 rows x 12 columns]

In [10]:
result_df5=df_dataset[df_dataset['U_DPTO'].isin(options4)] #Se asigna a result_df5 el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options4
result_df5 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
0             91       1       2        2              6            NaN   
1             91       1       1        9              1            2.0   
2             91       1       2        3              6            NaN   
3             91       1       2        8              1            2.0   
4             91       1       1        1              6            NaN   
...          ...     ...     ...      ...            ...            ...   
27704596      94     888       2        4              1            1.0   
27704597      94     888       2        2              1            1.0   
27704598      94     888       2        1              1            1.0   
27704599      94     888       2        1              1            1.0   
27704600      94     888       2        2              1            1.0   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
0                   NaN              NaN               NaN         1.0   
1                   2.0              NaN               NaN         1.0   
2                   NaN              NaN               NaN         1.0   
3                   2.0              NaN               NaN         1.0   
4                   NaN              NaN               NaN         NaN   
...                 ...              ...               ...         ...   
27704596            2.0              NaN               NaN         1.0   
27704597            2.0              NaN               NaN         2.0   
27704598            2.0              NaN               NaN         NaN   
27704599            2.0              NaN               NaN         NaN   
27704600            2.0              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
0                   1.0        NaN  
1                   3.0        2.0  
2                   2.0        9.0  
3                   4.0        1.0  
4                   NaN        NaN  
...                 ...        ...  
27704596            2.0        7.0  
27704597            1.0        NaN  
27704598            NaN        NaN  
27704599            NaN        NaN  
27704600            2.0        NaN  

[10704228 rows x 12 columns]

In [11]:
result_df6=df_dataset[df_dataset['U_DPTO'].isin(options5)] #Se asigna a result_df6 el dataset en el cual solo están los departamentos 
#Que coinciden con los códigos que hay en options5
result_df6 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
27704601      95       1       1       11              6            NaN   
27704602      95       1       2       10              6            NaN   
27704603      95       1       1        2              6            NaN   
27704604      95       1       1       10              6            NaN   
27704605      95       1       2        6              6            NaN   
...          ...     ...     ...      ...            ...            ...   
44164412      99     773       2        4              6            NaN   
44164413      99     773       2        8              6            NaN   
44164414      99     773       2        3              6            NaN   
44164415      99     773       1        3              6            NaN   
44164416      99     773       1        9              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
27704601            NaN              NaN               NaN         1.0   
27704602            NaN              NaN               NaN         1.0   
27704603            NaN              NaN               NaN         1.0   
27704604            NaN              NaN               NaN         1.0   
27704605            NaN              NaN               NaN         1.0   
...                 ...              ...               ...         ...   
44164412            NaN              NaN               NaN         1.0   
44164413            NaN              NaN               NaN         1.0   
44164414            NaN              NaN               NaN         1.0   
44164415            NaN              NaN               NaN         1.0   
44164416            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
27704601            2.0        3.0  
27704602            3.0        7.0  
27704603            2.0        NaN  
27704604            2.0        4.0  
27704605            7.0        7.0  
...                 ...        ...  
44164412            3.0        NaN  
44164413            8.0        NaN  
44164414            2.0        NaN  
44164415            2.0        NaN  
44164416            7.0        NaN  

[470610 rows x 12 columns]

In [12]:
result_df['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df

array([19, 27, 54, 63, 73, 76], dtype=int64)

In [13]:
result_df2['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df2

array([15, 18, 20, 41, 44], dtype=int64)

In [14]:
result_df3['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df3

array([ 5, 17, 47, 50, 66, 70], dtype=int64)

In [15]:
result_df4['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df4

array([ 8, 13, 23, 52, 88, 68], dtype=int64)

In [16]:
result_df5['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df5

array([91, 81, 11, 85, 25, 94], dtype=int64)

In [17]:
result_df6['U_DPTO'].unique() #Se verifican los códigos de departamentos que quedaron en el dataset result_df6

array([95, 86, 97, 99], dtype=int64)

In [18]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrados10.csv'
result_df.to_csv(export_dir, index=False, header=True)

In [19]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir2 = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrado11.csv'
result_df2.to_csv(export_dir2, index=False, header=True)

In [20]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir3 = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrado12.csv'
result_df3.to_csv(export_dir3, index=False, header=True)

In [21]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir4 = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrado13.csv'
result_df4.to_csv(export_dir4, index=False, header=True)

In [22]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir5 = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrado14.csv'
result_df5.to_csv(export_dir5, index=False, header=True)

In [23]:
#Se procede a asignar la dirección en la cual se desea almacenar el csv de cada uno de los datasets creados
export_dir6 = 'TG2022_Datos/Departamentos_CSV/Mpios_filtrados/Pre_Departamentos_personas_filtrado15.csv'
result_df6.to_csv(export_dir6, index=False, header=True)

In [24]:
result_df.isnull().sum() #Se revisan la cantidad de filas nulas para cada columna en result_df

U_DPTO                    0
U_MPIO                    0
P_SEXO                    0
P_EDADR                   0
PA1_GRP_ETNIC             0
PA_HABLA_LENG       8114805
PB_OTRAS_LENG       8114805
PB1_QOTRAS_LENG     8528642
PA1_CALIDAD_SERV    7886246
P_ALFABETA           569888
P_NIVEL_ANOSR        569888
P_TRABAJO           1259316
dtype: int64

In [33]:
result_df6 #Se imprime el dataset

U_DPTO  U_MPIO  P_SEXO  P_EDADR  PA1_GRP_ETNIC  PA_HABLA_LENG  \
27704601      95       1       1       11              6            NaN   
27704602      95       1       2       10              6            NaN   
27704603      95       1       1        2              6            NaN   
27704604      95       1       1       10              6            NaN   
27704605      95       1       2        6              6            NaN   
...          ...     ...     ...      ...            ...            ...   
44164412      99     773       2        4              6            NaN   
44164413      99     773       2        8              6            NaN   
44164414      99     773       2        3              6            NaN   
44164415      99     773       1        3              6            NaN   
44164416      99     773       1        9              6            NaN   

          PB_OTRAS_LENG  PB1_QOTRAS_LENG  PA1_CALIDAD_SERV  P_ALFABETA  \
27704601            NaN              NaN               NaN         1.0   
27704602            NaN              NaN               NaN         1.0   
27704603            NaN              NaN               NaN         1.0   
27704604            NaN              NaN               NaN         1.0   
27704605            NaN              NaN               NaN         1.0   
...                 ...              ...               ...         ...   
44164412            NaN              NaN               NaN         1.0   
44164413            NaN              NaN               NaN         1.0   
44164414            NaN              NaN               NaN         1.0   
44164415            NaN              NaN               NaN         1.0   
44164416            NaN              NaN               NaN         1.0   

          P_NIVEL_ANOSR  P_TRABAJO  
27704601            2.0        3.0  
27704602            3.0        7.0  
27704603            2.0        NaN  
27704604            2.0        4.0  
27704605            7.0        7.0  
...                 ...        ...  
44164412            3.0        NaN  
44164413            8.0        NaN  
44164414            2.0        NaN  
44164415            2.0        NaN  
44164416            7.0        NaN  

[470610 rows x 12 columns]